language: android
dist: trusty
env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.0
    - CLOUD_PROJECT_ID=radixdlt-android-wallet

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS
    - build-tools-28.0.3
    - android-$ANDROID_API
    - add-on
    - extra

before_install:
  - openssl aes-256-cbc -K $encrypted_a9f4e0427553_key -iv $encrypted_a9f4e0427553_iv
    -in travis/radixdlt-android-wallet-0ed2ebec4e7b.json.enc -out travis/radixdlt-android-wallet-0ed2ebec4e7b.json
    -d

before_script:
  # get gcloud
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export $CLOUDSDK_CORE_DISABLE_PROMPTS; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc # Add gcloud to $PATH
  - gcloud version #check the version of gcloud
  - gcloud config set project $CLOUD_PROJECT_ID
  # Activate cloud credentials
  - gcloud auth activate-service-account --key-file travis/radixdlt-android-wallet-0ed2ebec4e7b.json
  # List available options for logging purpose only (so that we can review available options)
  - gcloud firebase test android models list
  - gcloud firebase test android versions list

jobs:
  include:
    - stage: Pipe
      script:
        - cp .android/debug.keystore /home/travis/.android/
        # Assemble and running Unit Tests
        - "./gradlew clean --stacktrace --console=plain --build-cache :app:assembleDummyDebug :app:assembleDummyDebugAndroidTest :app:testDummyDebugUnitTest"
        # Instrumentation Tests
        - gcloud firebase test android run
          --use-orchestrator
          --type instrumentation
          --app ./app/build/outputs/apk/dummy/debug/app-dummy-debug.apk
          --test ./app/build/outputs/apk/androidTest/dummy/debug/app-dummy-debug-androidTest.apk
          --device model=walleye,version=28,locale=en,orientation=portrait
